wamv_camera:
    - name: front_left_camera
      visualize: True
      x: 0.85
      y: 0.16
      z: 1.5
      R: 0.0
      P: ${radians(10)}
      Y: 0.0
      post_Y: 0.0
    - name: front_right_camera
      visualize: True
      x: 0.85
      y: -0.16
      z: 1.5
      R: 0.0
      P: ${radians(10)}
      Y: 0.0
      post_Y: 0.0
    - name: far_left_camera
      visualize: True
      x: 0.63
      y: 0.5
      z: 1.38
      R: 0.0
      P: ${radians(15)}
      Y: ${radians(90)}
      post_Y: 0.0
wamv_gps:
    - name: gps_wamv
      x: 0.54
      y: 0.0
      z: 1.3
      R: 0.0
      P: 0.0
      Y: 0.0
wamv_imu:
    - name: imu_wamv
      x: 0.45
      y: 0
      z: 1.3
      R: 0.0
      P: 0.0
      Y: 0.0
lidar:
    - name: lidar_front_wamv
      type: 16_beam
      x: 0.82
      y: 0.0
      z: 1.6
      R: 0.0
      P: ${radians(12)}
      Y: 0.0
      post_Y: 0.0
    - name: lidar_back_wamv
      type: 16_beam
      x: -0.85
      y: 0.0
      z: 1.75
      R: 0.0
      P: ${radians(25)}
      Y: 0.0
      post_Y: 0.0
wamv_ball_shooter:
    - name: ball_shooter
      x: 0.9
      y: 0.0
      z: 1.3
      pitch: ${radians(-10)}
      yaw: 0.0
wamv_pinger:
    - sensor_name: receiver
      position: 1.0 0 -1.0
