wamv_camera:
    - name: front_camera
      x: 0.75
      y: 0.0
      P: ${radians(15)}
wamv_gps:
    - name: gps_wamv
      x: -0.85
wamv_imu:
    - name: imu_wamv
      y: -0.2
lidar:
    - name: lidar_wamv
      type: 16_beam
      P: ${radians(8)}
wamv_ball_shooter:
    - name: ball_shooter
      x: 0.5
      y: -0.25
      z: 1.3
      pitch: ${radians(-20)}
      yaw: 0
